"""Feeds the Elevation Index from our own data.

Writes ei-auto.js: every tracked team's games and box-score stats (computed
from the play-by-play), the strength of every opponent (from The Bot's
ratings, FCS included), each team's next game and the current week.
Nothing in it is typed in by hand or taken from ESPN, the AP poll or any
other ranking.
"""
from __future__ import annotations

import json
from datetime import timedelta

import numpy as np
import pandas as pd

import plays


def site_week(start: pd.Series, week: pd.Series) -> pd.Series:
    """Elevation Change numbers the late-August opener weekend Week 0."""
    local = start - pd.Timedelta(hours=6)
    wk1 = local[week == 1]
    if not len(wk1):
        return week
    cutoff = wk1.max() - pd.Timedelta(days=4)
    return np.where((week == 1) & (local < cutoff), 0, week)


def build(season: int, sg: pd.DataFrame, T: pd.DataFrame, west: dict, out_path) -> dict:
    """
    sg:   this season's games (from data.build_games)
    T:    team ratings (team_id, name, div, net, rank) for every team in the season
    west: site id -> data name for the tracked teams
    """
    by_name = {v: k for k, v in west.items()}
    T = T.copy()
    fbs = T[T["div"] == "fbs"].sort_values("net", ascending=False)
    fbs_nets = fbs.net.to_numpy()
    natrank = dict(zip(fbs.name, range(1, len(fbs) + 1)))
    fcs = T[T["div"] != "fbs"].sort_values("net", ascending=False)
    fcs_rank = dict(zip(fcs.name, range(1, len(fcs) + 1)))

    def equiv(net):  # where a team with this rating would rank in FBS
        return int(1 + (fbs_nets > net).sum())

    g = sg.copy()
    g["sw"] = site_week(g.start, g.week)
    tracked = g[g.home_team.isin(by_name) | g.away_team.isin(by_name)]
    done = tracked[tracked.completed]

    box = plays.box_scores(season).set_index(["game_id", "team"])

    def stats(gid, team, opp):
        if (gid, team) not in box.index or (gid, opp) not in box.index:
            return None
        a, b = box.loc[(gid, team)], box.loc[(gid, opp)]
        s = {"yds": int(a.yds), "oppYds": int(b.yds), "ypp": round(float(a.ypp), 1), "oppYpp": round(float(b.ypp), 1),
             "explosive": int(a.explosive), "oppExplosive": int(b.explosive),
             "to": int(a.to), "oppTo": int(b.to), "sacks": int(b.sacked), "sacksAllowed": int(a.sacked)}
        if a.third_att:
            s["thirdPct"] = int(round(100 * a.third_conv / a.third_att))
        if b.third_att:
            s["oppThirdPct"] = int(round(100 * b.third_conv / b.third_att))
        return s

    games, opps = [], {}
    for _, x in done.sort_values("start").iterrows():
        for side, other in (("home", "away"), ("away", "home")):
            name = x[f"{side}_team"]
            if name not in by_name:
                continue
            oname = x[f"{other}_team"]
            opp = by_name.get(oname, oname)
            if oname not in by_name and oname not in opps:
                row = T[T.name == oname]
                if len(row) and row["div"].iat[0] == "fbs":
                    opps[oname] = {"natRank": natrank.get(oname, 100), "fcs": False}
                else:
                    net = float(row.net.iat[0]) if len(row) else -25.0
                    eq = equiv(net)
                    fr = fcs_rank.get(oname)
                    o = {"fcs": True, "equivRank": eq, "strong": eq <= 110}
                    if fr and fr <= 25 and eq <= 128:
                        o["fcsRank"] = fr
                    opps[oname] = o
            rec = {"team": by_name[name], "week": int(x.sw),
                   "date": (x.start - timedelta(hours=6)).strftime("%Y-%m-%d"), "opp": opp,
                   "site": "N" if x.neutral_site else ("H" if side == "home" else "A"),
                   "pf": int(x[f"{side}_points"]), "pa": int(x[f"{other}_points"])}
            st = stats(int(x.game_id), name, oname)
            if st:
                rec["stats"] = st
            games.append(rec)

    # next game for each tracked team
    nxt = {}
    pending = tracked[~tracked.completed].sort_values("start")
    cur_week = int(done.sw.max()) if len(done) else 0
    for sid, name in west.items():
        pg = pending[(pending.home_team == name) | (pending.away_team == name)]
        if not len(pg):
            nxt[sid] = "Season complete"
            continue
        x = pg.iloc[0]
        if int(x.sw) > cur_week + 1:
            nxt[sid] = "Bye"
            continue
        home = x.home_team == name
        oname = x.away_team if home else x.home_team
        nxt[sid] = ("vs " if home or x.neutral_site else "at ") + oname

    bot_rank = {sid: natrank.get(name) for sid, name in west.items() if natrank.get(name)}
    js = ("/* ===================================================================\n"
          "   ELEVATION INDEX — AUTOMATIC DATA (generated by model/run.py)\n"
          "   Do not edit by hand: it is rebuilt after every run of The Bot.\n"
          "   Games and scores come from the public results archive; box-score\n"
          "   stats are computed from play-by-play; opponent strength is The\n"
          "   Bot's current national rank (FCS teams are placed where their\n"
          "   rating would rank among FBS teams).\n"
          "   =================================================================== */\n"
          f"const BOT_NATRANK = {json.dumps(bot_rank)};\n"
          f"const OPPONENTS = {json.dumps(opps, ensure_ascii=False, indent=1)};\n"
          f"const GAMES = {json.dumps(games, ensure_ascii=False, separators=(',', ':')).replace('},{', '},\n{')};\n"
          f"const NEXT = {json.dumps(nxt, ensure_ascii=False, indent=1)};\n"
          f"const CURRENT_WEEK = {cur_week};\n")
    with open(out_path, "w") as f:
        f.write(js)
    return {"games": len(games), "with_stats": sum("stats" in g_ for g_ in games), "opponents": len(opps), "week": cur_week}
