/* ===================================================================
   ELEVATION INDEX — AUTOMATIC DATA (generated by model/run.py)
   Do not edit by hand: it is rebuilt after every run of The Bot.
   Games and scores come from the public results archive; box-score
   stats are computed from play-by-play; opponent strength is The
   Bot's current national rank (FCS teams are placed where their
   rating would rank among FBS teams).
   =================================================================== */
const BOT_NATRANK = {"AFA": 92, "HAW": 124, "NEV": 104, "UNM": 63, "NDSU": 68, "NIU": 126, "SJSU": 115, "UNLV": 97, "UTEP": 128, "WYO": 119, "BSU": 40, "CSU": 98, "FRES": 79, "ORST": 57, "SDSU": 88, "TXST": 69, "USU": 89, "WSU": 73, "NMSU": 127, "SAC": 137};
const OPPONENTS = {
 "USC": {
  "natRank": 21,
  "fcs": false
 },
 "Jacksonville State": {
  "natRank": 103,
  "fcs": false
 },
 "Eastern Michigan": {
  "natRank": 130,
  "fcs": false
 },
 "Stanford": {
  "natRank": 94,
  "fcs": false
 },
 "Florida State": {
  "natRank": 49,
  "fcs": false
 },
 "Memphis": {
  "natRank": 74,
  "fcs": false
 },
 "Oklahoma": {
  "natRank": 20,
  "fcs": false
 },
 "Houston": {
  "natRank": 30,
  "fcs": false
 },
 "Duquesne": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Texas": {
  "natRank": 7,
  "fcs": false
 },
 "Oregon": {
  "natRank": 6,
  "fcs": false
 },
 "Fordham": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Iowa": {
  "natRank": 13,
  "fcs": false
 },
 "Idaho State": {
  "fcs": true,
  "equivRank": 122,
  "strong": false,
  "fcsRank": 10
 },
 "Mercyhurst": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Portland State": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Central Michigan": {
  "natRank": 129,
  "fcs": false
 },
 "Mississippi Valley State": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Western Kentucky": {
  "natRank": 111,
  "fcs": false
 },
 "Washington": {
  "natRank": 41,
  "fcs": false
 },
 "Kansas State": {
  "natRank": 27,
  "fcs": false
 },
 "UTSA": {
  "natRank": 61,
  "fcs": false
 },
 "North Texas": {
  "natRank": 66,
  "fcs": false
 },
 "Northern Colorado": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Southern Utah": {
  "fcs": true,
  "equivRank": 136,
  "strong": false
 },
 "Illinois State": {
  "fcs": true,
  "equivRank": 121,
  "strong": false,
  "fcsRank": 9
 },
 "UCLA": {
  "natRank": 12,
  "fcs": false
 },
 "Texas Tech": {
  "natRank": 15,
  "fcs": false
 },
 "Cal Poly": {
  "fcs": true,
  "equivRank": 138,
  "strong": false
 },
 "Texas Southern": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Montana State": {
  "fcs": true,
  "equivRank": 71,
  "strong": true,
  "fcsRank": 1
 },
 "Utah": {
  "natRank": 5,
  "fcs": false
 },
 "Michigan": {
  "natRank": 25,
  "fcs": false
 },
 "Middle Tennessee": {
  "natRank": 123,
  "fcs": false
 },
 "BYU": {
  "natRank": 17,
  "fcs": false
 },
 "James Madison": {
  "natRank": 42,
  "fcs": false
 },
 "South Dakota": {
  "fcs": true,
  "equivRank": 105,
  "strong": true,
  "fcsRank": 3
 },
 "Arizona": {
  "natRank": 44,
  "fcs": false
 },
 "Montana": {
  "fcs": true,
  "equivRank": 115,
  "strong": false,
  "fcsRank": 6
 },
 "Toledo": {
  "natRank": 54,
  "fcs": false
 },
 "Akron": {
  "natRank": 132,
  "fcs": false
 },
 "Georgia State": {
  "natRank": 96,
  "fcs": false
 },
 "Western Michigan": {
  "natRank": 83,
  "fcs": false
 },
 "Incarnate Word": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Troy": {
  "natRank": 100,
  "fcs": false
 },
 "Massachusetts": {
  "natRank": 120,
  "fcs": false
 },
 "Rice": {
  "natRank": 122,
  "fcs": false
 }
};
const GAMES = [{"team":"SJSU","week":0,"date":"2026-08-29","opp":"USC","site":"A","pf":26,"pa":42,"stats":{"yds":330,"oppYds":512,"ypp":5.9,"oppYpp":6.8,"explosive":8,"oppExplosive":8,"to":0,"oppTo":1,"sacks":2,"sacksAllowed":1,"thirdPct":45,"oppThirdPct":69}},
{"team":"NDSU","week":0,"date":"2026-08-29","opp":"Jacksonville State","site":"H","pf":33,"pa":7,"stats":{"yds":371,"oppYds":167,"ypp":5.6,"oppYpp":3.4,"explosive":9,"oppExplosive":4,"to":1,"oppTo":1,"sacks":3,"sacksAllowed":2,"thirdPct":36,"oppThirdPct":20}},
{"team":"SAC","week":0,"date":"2026-08-29","opp":"Eastern Michigan","site":"A","pf":17,"pa":28},
{"team":"HAW","week":0,"date":"2026-08-29","opp":"Stanford","site":"A","pf":27,"pa":37,"stats":{"yds":335,"oppYds":483,"ypp":4.6,"oppYpp":6.8,"explosive":6,"oppExplosive":10,"to":0,"oppTo":0,"sacks":0,"sacksAllowed":2,"thirdPct":41,"oppThirdPct":47}},
{"team":"NMSU","week":0,"date":"2026-08-29","opp":"Florida State","site":"A","pf":17,"pa":34,"stats":{"yds":330,"oppYds":436,"ypp":5.1,"oppYpp":6.9,"explosive":6,"oppExplosive":10,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":2,"thirdPct":59,"oppThirdPct":62}},
{"team":"UNLV","week":0,"date":"2026-08-29","opp":"Memphis","site":"H","pf":21,"pa":27,"stats":{"yds":491,"oppYds":411,"ypp":6.3,"oppYpp":7.1,"explosive":9,"oppExplosive":11,"to":0,"oppTo":0,"sacks":1,"sacksAllowed":6,"thirdPct":20,"oppThirdPct":27}},
{"team":"SJSU","week":1,"date":"2026-09-04","opp":"Eastern Michigan","site":"A","pf":27,"pa":21,"stats":{"yds":456,"oppYds":299,"ypp":6.2,"oppYpp":4.5,"explosive":10,"oppExplosive":2,"to":1,"oppTo":1,"sacks":0,"sacksAllowed":1,"thirdPct":31,"oppThirdPct":19}},
{"team":"UTEP","week":1,"date":"2026-09-04","opp":"Oklahoma","site":"A","pf":0,"pa":51,"stats":{"yds":180,"oppYds":408,"ypp":3.4,"oppYpp":6.9,"explosive":3,"oppExplosive":9,"to":0,"oppTo":0,"sacks":1,"sacksAllowed":4,"thirdPct":15,"oppThirdPct":55}},
{"team":"FRES","week":1,"date":"2026-09-04","opp":"USC","site":"A","pf":0,"pa":39,"stats":{"yds":131,"oppYds":553,"ypp":3.3,"oppYpp":8.3,"explosive":2,"oppExplosive":12,"to":1,"oppTo":0,"sacks":0,"sacksAllowed":2,"thirdPct":22,"oppThirdPct":62}},
{"team":"ORST","week":1,"date":"2026-09-05","opp":"Houston","site":"A","pf":20,"pa":33,"stats":{"yds":413,"oppYds":545,"ypp":5.7,"oppYpp":7.7,"explosive":7,"oppExplosive":13,"to":0,"oppTo":1,"sacks":1,"sacksAllowed":4,"thirdPct":27,"oppThirdPct":54}},
{"team":"AFA","week":1,"date":"2026-09-05","opp":"Duquesne","site":"H","pf":34,"pa":0,"stats":{"yds":428,"oppYds":105,"ypp":5.9,"oppYpp":2.5,"explosive":8,"oppExplosive":1,"to":0,"oppTo":2,"sacks":1,"sacksAllowed":0,"thirdPct":60,"oppThirdPct":27}},
{"team":"TXST","week":1,"date":"2026-09-05","opp":"Texas","site":"A","pf":7,"pa":59,"stats":{"yds":343,"oppYds":525,"ypp":4.9,"oppYpp":7.5,"explosive":7,"oppExplosive":13,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":2,"thirdPct":57,"oppThirdPct":73}},
{"team":"BSU","week":1,"date":"2026-09-05","opp":"Oregon","site":"A","pf":27,"pa":34,"stats":{"yds":271,"oppYds":524,"ypp":4.2,"oppYpp":8.2,"explosive":4,"oppExplosive":9,"to":0,"oppTo":0,"sacks":1,"sacksAllowed":3,"thirdPct":27,"oppThirdPct":33}},
{"team":"NDSU","week":1,"date":"2026-09-05","opp":"Fordham","site":"H","pf":38,"pa":0,"stats":{"yds":365,"oppYds":150,"ypp":5.8,"oppYpp":3.2,"explosive":8,"oppExplosive":2,"to":0,"oppTo":3,"sacks":3,"sacksAllowed":3,"thirdPct":50,"oppThirdPct":33}},
{"team":"NIU","week":1,"date":"2026-09-05","opp":"Iowa","site":"A","pf":0,"pa":40,"stats":{"yds":119,"oppYds":460,"ypp":2.2,"oppYpp":6.1,"explosive":4,"oppExplosive":10,"to":1,"oppTo":1,"sacks":0,"sacksAllowed":6,"thirdPct":20,"oppThirdPct":38}},
{"team":"CSU","week":1,"date":"2026-09-05","opp":"WYO","site":"H","pf":35,"pa":13,"stats":{"yds":397,"oppYds":270,"ypp":6.4,"oppYpp":5.1,"explosive":7,"oppExplosive":7,"to":0,"oppTo":3,"sacks":2,"sacksAllowed":0,"thirdPct":53,"oppThirdPct":0}},
{"team":"WYO","week":1,"date":"2026-09-05","opp":"CSU","site":"A","pf":13,"pa":35,"stats":{"yds":270,"oppYds":397,"ypp":5.1,"oppYpp":6.4,"explosive":7,"oppExplosive":7,"to":3,"oppTo":0,"sacks":0,"sacksAllowed":2,"thirdPct":0,"oppThirdPct":53}},
{"team":"USU","week":1,"date":"2026-09-05","opp":"Idaho State","site":"H","pf":17,"pa":29,"stats":{"yds":429,"oppYds":246,"ypp":4.9,"oppYpp":4.0,"explosive":6,"oppExplosive":2,"to":4,"oppTo":0,"sacks":2,"sacksAllowed":2,"thirdPct":60,"oppThirdPct":33}},
{"team":"NMSU","week":1,"date":"2026-09-05","opp":"Mercyhurst","site":"H","pf":51,"pa":14,"stats":{"yds":537,"oppYds":243,"ypp":8.8,"oppYpp":4.3,"explosive":11,"oppExplosive":5,"to":0,"oppTo":1,"sacks":2,"sacksAllowed":1,"thirdPct":54,"oppThirdPct":38}},
{"team":"SDSU","week":1,"date":"2026-09-05","opp":"Portland State","site":"H","pf":53,"pa":20,"stats":{"yds":360,"oppYds":382,"ypp":6.5,"oppYpp":4.7,"explosive":9,"oppExplosive":4,"to":1,"oppTo":2,"sacks":1,"sacksAllowed":0,"thirdPct":58,"oppThirdPct":37}},
{"team":"HAW","week":1,"date":"2026-09-05","opp":"UNLV","site":"H","pf":6,"pa":21,"stats":{"yds":287,"oppYds":373,"ypp":3.7,"oppYpp":6.2,"explosive":7,"oppExplosive":8,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":5,"thirdPct":45,"oppThirdPct":47}},
{"team":"UNLV","week":1,"date":"2026-09-05","opp":"HAW","site":"A","pf":21,"pa":6,"stats":{"yds":373,"oppYds":287,"ypp":6.2,"oppYpp":3.7,"explosive":8,"oppExplosive":7,"to":0,"oppTo":1,"sacks":5,"sacksAllowed":1,"thirdPct":47,"oppThirdPct":45}},
{"team":"UNM","week":1,"date":"2026-09-05","opp":"Central Michigan","site":"H","pf":38,"pa":7,"stats":{"yds":352,"oppYds":155,"ypp":5.3,"oppYpp":3.3,"explosive":7,"oppExplosive":2,"to":0,"oppTo":1,"sacks":3,"sacksAllowed":1,"thirdPct":50,"oppThirdPct":18}},
{"team":"SAC","week":1,"date":"2026-09-05","opp":"Mississippi Valley State","site":"H","pf":52,"pa":0,"stats":{"yds":464,"oppYds":85,"ypp":6.7,"oppYpp":4.0,"explosive":9,"oppExplosive":2,"to":1,"oppTo":0,"sacks":0,"sacksAllowed":0,"thirdPct":50,"oppThirdPct":50}},
{"team":"NEV","week":1,"date":"2026-09-05","opp":"Western Kentucky","site":"H","pf":49,"pa":14,"stats":{"yds":490,"oppYds":365,"ypp":8.8,"oppYpp":4.6,"explosive":9,"oppExplosive":5,"to":1,"oppTo":0,"sacks":3,"sacksAllowed":0,"thirdPct":50,"oppThirdPct":41}},
{"team":"WSU","week":1,"date":"2026-09-06","opp":"Washington","site":"A","pf":10,"pa":24,"stats":{"yds":236,"oppYds":405,"ypp":4.4,"oppYpp":6.4,"explosive":3,"oppExplosive":10,"to":2,"oppTo":0,"sacks":0,"sacksAllowed":3,"thirdPct":0,"oppThirdPct":31}},
{"team":"WSU","week":2,"date":"2026-09-12","opp":"Kansas State","site":"A","pf":7,"pa":34,"stats":{"yds":171,"oppYds":487,"ypp":3.4,"oppYpp":6.7,"explosive":4,"oppExplosive":7,"to":0,"oppTo":1,"sacks":0,"sacksAllowed":4,"thirdPct":17,"oppThirdPct":62}},
{"team":"TXST","week":2,"date":"2026-09-12","opp":"UTSA","site":"H","pf":26,"pa":31,"stats":{"yds":474,"oppYds":383,"ypp":6.1,"oppYpp":5.2,"explosive":7,"oppExplosive":6,"to":3,"oppTo":0,"sacks":0,"sacksAllowed":0,"thirdPct":53,"oppThirdPct":20}},
{"team":"USU","week":2,"date":"2026-09-12","opp":"Washington","site":"A","pf":14,"pa":16,"stats":{"yds":267,"oppYds":354,"ypp":4.7,"oppYpp":4.8,"explosive":6,"oppExplosive":6,"to":3,"oppTo":0,"sacks":2,"sacksAllowed":3,"thirdPct":46,"oppThirdPct":38}},
{"team":"UNLV","week":2,"date":"2026-09-12","opp":"North Texas","site":"A","pf":6,"pa":44,"stats":{"yds":312,"oppYds":450,"ypp":4.5,"oppYpp":6.8,"explosive":6,"oppExplosive":12,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":3,"thirdPct":47,"oppThirdPct":54}},
{"team":"WYO","week":2,"date":"2026-09-12","opp":"Northern Colorado","site":"H","pf":21,"pa":13,"stats":{"yds":309,"oppYds":333,"ypp":5.4,"oppYpp":5.5,"explosive":10,"oppExplosive":7,"to":0,"oppTo":2,"sacks":3,"sacksAllowed":1,"thirdPct":50,"oppThirdPct":33}},
{"team":"UNM","week":2,"date":"2026-09-12","opp":"Mercyhurst","site":"H","pf":70,"pa":7,"stats":{"yds":428,"oppYds":182,"ypp":6.5,"oppYpp":3.3,"explosive":10,"oppExplosive":4,"to":0,"oppTo":5,"sacks":5,"sacksAllowed":2,"thirdPct":42,"oppThirdPct":15}},
{"team":"BSU","week":2,"date":"2026-09-12","opp":"Memphis","site":"H","pf":38,"pa":20,"stats":{"yds":581,"oppYds":518,"ypp":8.1,"oppYpp":10.0,"explosive":13,"oppExplosive":10,"to":0,"oppTo":1,"sacks":2,"sacksAllowed":0,"thirdPct":46,"oppThirdPct":12}},
{"team":"CSU","week":2,"date":"2026-09-12","opp":"Southern Utah","site":"H","pf":58,"pa":24,"stats":{"yds":694,"oppYds":432,"ypp":10.8,"oppYpp":7.6,"explosive":12,"oppExplosive":12,"to":1,"oppTo":2,"sacks":2,"sacksAllowed":1,"thirdPct":58,"oppThirdPct":42}},
{"team":"NIU","week":2,"date":"2026-09-12","opp":"Illinois State","site":"H","pf":24,"pa":28,"stats":{"yds":310,"oppYds":258,"ypp":4.8,"oppYpp":4.3,"explosive":5,"oppExplosive":5,"to":1,"oppTo":2,"sacks":3,"sacksAllowed":3,"thirdPct":43,"oppThirdPct":64}},
{"team":"SDSU","week":2,"date":"2026-09-12","opp":"UCLA","site":"A","pf":10,"pa":28,"stats":{"yds":167,"oppYds":371,"ypp":3.2,"oppYpp":5.8,"explosive":2,"oppExplosive":6,"to":1,"oppTo":1,"sacks":2,"sacksAllowed":2,"thirdPct":17,"oppThirdPct":40}},
{"team":"ORST","week":2,"date":"2026-09-12","opp":"Texas Tech","site":"H","pf":24,"pa":35,"stats":{"yds":477,"oppYds":354,"ypp":6.7,"oppYpp":4.9,"explosive":11,"oppExplosive":5,"to":1,"oppTo":0,"sacks":4,"sacksAllowed":2,"thirdPct":27,"oppThirdPct":50}},
{"team":"SJSU","week":2,"date":"2026-09-12","opp":"Cal Poly","site":"H","pf":30,"pa":20,"stats":{"yds":481,"oppYds":348,"ypp":6.2,"oppYpp":5.1,"explosive":9,"oppExplosive":9,"to":0,"oppTo":2,"sacks":4,"sacksAllowed":0,"thirdPct":25,"oppThirdPct":47}},
{"team":"UTEP","week":2,"date":"2026-09-12","opp":"Texas Southern","site":"H","pf":51,"pa":10,"stats":{"yds":489,"oppYds":167,"ypp":9.1,"oppYpp":3.6,"explosive":8,"oppExplosive":4,"to":0,"oppTo":1,"sacks":2,"sacksAllowed":1,"thirdPct":50,"oppThirdPct":33}},
{"team":"AFA","week":2,"date":"2026-09-12","opp":"NDSU","site":"H","pf":32,"pa":38,"stats":{"yds":382,"oppYds":382,"ypp":5.9,"oppYpp":6.6,"explosive":6,"oppExplosive":8,"to":1,"oppTo":1,"sacks":0,"sacksAllowed":1,"thirdPct":43,"oppThirdPct":33}},
{"team":"NDSU","week":2,"date":"2026-09-12","opp":"AFA","site":"A","pf":38,"pa":32,"stats":{"yds":382,"oppYds":382,"ypp":6.6,"oppYpp":5.9,"explosive":8,"oppExplosive":6,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":0,"thirdPct":33,"oppThirdPct":43}},
{"team":"FRES","week":2,"date":"2026-09-12","opp":"SAC","site":"H","pf":49,"pa":3,"stats":{"yds":542,"oppYds":269,"ypp":8.7,"oppYpp":4.3,"explosive":10,"oppExplosive":4,"to":0,"oppTo":1,"sacks":0,"sacksAllowed":0,"thirdPct":38,"oppThirdPct":23}},
{"team":"SAC","week":2,"date":"2026-09-12","opp":"FRES","site":"A","pf":3,"pa":49,"stats":{"yds":269,"oppYds":542,"ypp":4.3,"oppYpp":8.7,"explosive":4,"oppExplosive":10,"to":1,"oppTo":0,"sacks":0,"sacksAllowed":0,"thirdPct":23,"oppThirdPct":38}},
{"team":"NEV","week":2,"date":"2026-09-12","opp":"Montana State","site":"H","pf":7,"pa":20,"stats":{"yds":271,"oppYds":319,"ypp":5.0,"oppYpp":5.2,"explosive":5,"oppExplosive":7,"to":3,"oppTo":0,"sacks":3,"sacksAllowed":0,"thirdPct":27,"oppThirdPct":38}},
{"team":"HAW","week":2,"date":"2026-09-12","opp":"NMSU","site":"H","pf":29,"pa":19,"stats":{"yds":431,"oppYds":404,"ypp":5.9,"oppYpp":6.3,"explosive":7,"oppExplosive":9,"to":0,"oppTo":3,"sacks":1,"sacksAllowed":1,"thirdPct":36,"oppThirdPct":40}},
{"team":"NMSU","week":2,"date":"2026-09-12","opp":"HAW","site":"A","pf":19,"pa":29,"stats":{"yds":404,"oppYds":431,"ypp":6.3,"oppYpp":5.9,"explosive":9,"oppExplosive":7,"to":3,"oppTo":0,"sacks":1,"sacksAllowed":1,"thirdPct":40,"oppThirdPct":36}},
{"team":"TXST","week":3,"date":"2026-09-19","opp":"North Texas","site":"H","pf":49,"pa":35},
{"team":"WYO","week":3,"date":"2026-09-19","opp":"Central Michigan","site":"A","pf":10,"pa":24,"stats":{"yds":331,"oppYds":370,"ypp":5.9,"oppYpp":5.8,"explosive":7,"oppExplosive":4,"to":2,"oppTo":0,"sacks":0,"sacksAllowed":0,"thirdPct":46,"oppThirdPct":38}},
{"team":"WSU","week":3,"date":"2026-09-19","opp":"Duquesne","site":"H","pf":48,"pa":7},
{"team":"USU","week":3,"date":"2026-09-19","opp":"Utah","site":"A","pf":0,"pa":33,"stats":{"yds":190,"oppYds":484,"ypp":3.7,"oppYpp":6.6,"explosive":3,"oppExplosive":10,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":3,"thirdPct":29,"oppThirdPct":65}},
{"team":"UTEP","week":3,"date":"2026-09-19","opp":"Michigan","site":"A","pf":17,"pa":52,"stats":{"yds":152,"oppYds":424,"ypp":3.3,"oppYpp":6.2,"explosive":4,"oppExplosive":9,"to":0,"oppTo":0,"sacks":1,"sacksAllowed":4,"thirdPct":18,"oppThirdPct":75}},
{"team":"NEV","week":3,"date":"2026-09-19","opp":"Middle Tennessee","site":"A","pf":20,"pa":27,"stats":{"yds":280,"oppYds":229,"ypp":4.9,"oppYpp":5.3,"explosive":5,"oppExplosive":3,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":1,"thirdPct":38,"oppThirdPct":18}},
{"team":"UNM","week":3,"date":"2026-09-19","opp":"Oklahoma","site":"A","pf":6,"pa":14,"stats":{"yds":189,"oppYds":299,"ypp":3.3,"oppYpp":5.3,"explosive":4,"oppExplosive":3,"to":0,"oppTo":2,"sacks":1,"sacksAllowed":6,"thirdPct":21,"oppThirdPct":47}},
{"team":"CSU","week":3,"date":"2026-09-19","opp":"BYU","site":"H","pf":23,"pa":41,"stats":{"yds":312,"oppYds":564,"ypp":5.0,"oppYpp":10.3,"explosive":5,"oppExplosive":11,"to":1,"oppTo":2,"sacks":0,"sacksAllowed":0,"thirdPct":50,"oppThirdPct":50}},
{"team":"SDSU","week":3,"date":"2026-09-19","opp":"James Madison","site":"H","pf":13,"pa":26},
{"team":"BSU","week":3,"date":"2026-09-19","opp":"South Dakota","site":"H","pf":38,"pa":24},
{"team":"SAC","week":3,"date":"2026-09-19","opp":"NDSU","site":"H","pf":10,"pa":31,"stats":{"yds":349,"oppYds":365,"ypp":5.3,"oppYpp":6.3,"explosive":9,"oppExplosive":9,"to":2,"oppTo":0,"sacks":0,"sacksAllowed":0,"thirdPct":44,"oppThirdPct":50}},
{"team":"NDSU","week":3,"date":"2026-09-19","opp":"SAC","site":"A","pf":31,"pa":10,"stats":{"yds":365,"oppYds":349,"ypp":6.3,"oppYpp":5.3,"explosive":9,"oppExplosive":9,"to":0,"oppTo":2,"sacks":0,"sacksAllowed":0,"thirdPct":50,"oppThirdPct":44}},
{"team":"NIU","week":3,"date":"2026-09-19","opp":"Arizona","site":"A","pf":17,"pa":42,"stats":{"yds":349,"oppYds":442,"ypp":5.2,"oppYpp":7.4,"explosive":5,"oppExplosive":10,"to":0,"oppTo":1,"sacks":4,"sacksAllowed":2,"thirdPct":38,"oppThirdPct":69}},
{"team":"ORST","week":3,"date":"2026-09-19","opp":"Montana","site":"H","pf":52,"pa":17},
{"team":"SJSU","week":3,"date":"2026-09-19","opp":"FRES","site":"H","pf":10,"pa":26},
{"team":"FRES","week":3,"date":"2026-09-19","opp":"SJSU","site":"A","pf":26,"pa":10},
{"team":"SDSU","week":4,"date":"2026-09-26","opp":"Toledo","site":"A","pf":16,"pa":41,"stats":{"yds":248,"oppYds":484,"ypp":4.1,"oppYpp":7.1,"explosive":4,"oppExplosive":8,"to":1,"oppTo":0,"sacks":0,"sacksAllowed":3,"thirdPct":23,"oppThirdPct":50}},
{"team":"CSU","week":4,"date":"2026-09-26","opp":"UTSA","site":"A","pf":45,"pa":59,"stats":{"yds":498,"oppYds":537,"ypp":6.5,"oppYpp":8.0,"explosive":6,"oppExplosive":11,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":1,"thirdPct":35,"oppThirdPct":64}},
{"team":"UNLV","week":4,"date":"2026-09-26","opp":"Akron","site":"A","pf":38,"pa":10,"stats":{"yds":493,"oppYds":303,"ypp":8.0,"oppYpp":5.1,"explosive":10,"oppExplosive":7,"to":0,"oppTo":3,"sacks":4,"sacksAllowed":0,"thirdPct":50,"oppThirdPct":38}},
{"team":"NIU","week":4,"date":"2026-09-26","opp":"Georgia State","site":"A","pf":14,"pa":35,"stats":{"yds":415,"oppYds":348,"ypp":5.9,"oppYpp":6.2,"explosive":12,"oppExplosive":9,"to":0,"oppTo":1,"sacks":0,"sacksAllowed":6,"thirdPct":23,"oppThirdPct":50}},
{"team":"WYO","week":4,"date":"2026-09-26","opp":"HAW","site":"H","pf":27,"pa":10,"stats":{"yds":403,"oppYds":335,"ypp":6.7,"oppYpp":5.0,"explosive":13,"oppExplosive":7,"to":0,"oppTo":0,"sacks":3,"sacksAllowed":3,"thirdPct":50,"oppThirdPct":36}},
{"team":"HAW","week":4,"date":"2026-09-26","opp":"WYO","site":"A","pf":10,"pa":27,"stats":{"yds":335,"oppYds":403,"ypp":5.0,"oppYpp":6.7,"explosive":7,"oppExplosive":13,"to":0,"oppTo":0,"sacks":3,"sacksAllowed":3,"thirdPct":36,"oppThirdPct":50}},
{"team":"BSU","week":4,"date":"2026-09-26","opp":"Western Michigan","site":"A","pf":32,"pa":7,"stats":{"yds":372,"oppYds":232,"ypp":6.0,"oppYpp":4.5,"explosive":8,"oppExplosive":5,"to":0,"oppTo":1,"sacks":1,"sacksAllowed":0,"thirdPct":71,"oppThirdPct":18}},
{"team":"NMSU","week":4,"date":"2026-09-26","opp":"UNM","site":"H","pf":18,"pa":42,"stats":{"yds":408,"oppYds":436,"ypp":5.9,"oppYpp":7.0,"explosive":10,"oppExplosive":12,"to":2,"oppTo":0,"sacks":2,"sacksAllowed":3,"thirdPct":43,"oppThirdPct":42}},
{"team":"UNM","week":4,"date":"2026-09-26","opp":"NMSU","site":"A","pf":42,"pa":18,"stats":{"yds":436,"oppYds":408,"ypp":7.0,"oppYpp":5.9,"explosive":12,"oppExplosive":10,"to":0,"oppTo":2,"sacks":3,"sacksAllowed":2,"thirdPct":42,"oppThirdPct":43}},
{"team":"TXST","week":4,"date":"2026-09-26","opp":"Incarnate Word","site":"H","pf":63,"pa":10,"stats":{"yds":646,"oppYds":358,"ypp":9.8,"oppYpp":4.0,"explosive":12,"oppExplosive":6,"to":0,"oppTo":2,"sacks":4,"sacksAllowed":1,"thirdPct":71,"oppThirdPct":33}},
{"team":"WSU","week":4,"date":"2026-09-26","opp":"Arizona","site":"H","pf":24,"pa":34,"stats":{"yds":340,"oppYds":436,"ypp":4.9,"oppYpp":6.2,"explosive":7,"oppExplosive":11,"to":1,"oppTo":1,"sacks":3,"sacksAllowed":3,"thirdPct":27,"oppThirdPct":47}},
{"team":"USU","week":4,"date":"2026-09-26","opp":"Troy","site":"H","pf":21,"pa":10,"stats":{"yds":412,"oppYds":401,"ypp":7.1,"oppYpp":4.9,"explosive":10,"oppExplosive":5,"to":1,"oppTo":3,"sacks":0,"sacksAllowed":1,"thirdPct":33,"oppThirdPct":31}},
{"team":"UTEP","week":4,"date":"2026-09-26","opp":"ORST","site":"H","pf":7,"pa":33,"stats":{"yds":199,"oppYds":452,"ypp":3.1,"oppYpp":8.1,"explosive":2,"oppExplosive":11,"to":1,"oppTo":1,"sacks":0,"sacksAllowed":7,"thirdPct":23,"oppThirdPct":50}},
{"team":"ORST","week":4,"date":"2026-09-26","opp":"UTEP","site":"A","pf":33,"pa":7,"stats":{"yds":452,"oppYds":199,"ypp":8.1,"oppYpp":3.1,"explosive":11,"oppExplosive":2,"to":1,"oppTo":1,"sacks":7,"sacksAllowed":0,"thirdPct":50,"oppThirdPct":23}},
{"team":"SAC","week":4,"date":"2026-09-26","opp":"Massachusetts","site":"H","pf":6,"pa":35,"stats":{"yds":324,"oppYds":338,"ypp":4.3,"oppYpp":6.5,"explosive":4,"oppExplosive":8,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":4,"thirdPct":40,"oppThirdPct":30}},
{"team":"FRES","week":4,"date":"2026-09-26","opp":"Rice","site":"H","pf":38,"pa":24,"stats":{"yds":489,"oppYds":468,"ypp":7.5,"oppYpp":7.5,"explosive":14,"oppExplosive":8,"to":0,"oppTo":1,"sacks":2,"sacksAllowed":0,"thirdPct":50,"oppThirdPct":36}},
{"team":"NEV","week":4,"date":"2026-09-26","opp":"AFA","site":"H","pf":33,"pa":36,"stats":{"yds":412,"oppYds":437,"ypp":6.2,"oppYpp":5.4,"explosive":9,"oppExplosive":10,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":4,"thirdPct":33,"oppThirdPct":44}},
{"team":"AFA","week":4,"date":"2026-09-26","opp":"NEV","site":"A","pf":36,"pa":33,"stats":{"yds":437,"oppYds":412,"ypp":5.4,"oppYpp":6.2,"explosive":10,"oppExplosive":9,"to":1,"oppTo":1,"sacks":4,"sacksAllowed":1,"thirdPct":44,"oppThirdPct":33}}];
const NEXT = {
 "AFA": "vs Navy",
 "HAW": "vs San José State",
 "NEV": "Bye",
 "UNM": "vs UTEP",
 "NDSU": "vs Wyoming",
 "NIU": "Bye",
 "SJSU": "at Hawai'i",
 "UNLV": "vs California",
 "UTEP": "at New Mexico",
 "WYO": "at North Dakota State",
 "BSU": "vs Utah State",
 "CSU": "vs Oregon State",
 "FRES": "at Washington State",
 "ORST": "at Colorado State",
 "SDSU": "vs Texas State",
 "TXST": "at San Diego State",
 "USU": "at Boise State",
 "WSU": "vs Fresno State",
 "NMSU": "vs Western Kentucky",
 "SAC": "Bye"
};
const CURRENT_WEEK = 4;
