/* ===================================================================
   ELEVATION INDEX — AUTOMATIC DATA (generated by model/run.py)
   Do not edit by hand: it is rebuilt after every run of The Bot.
   Games and scores come from the public results archive and NCAA.com;
   box-score stats are NCAA official team stats (explosive plays from
   play-by-play); opponent strength is The
   Bot's current national rank (FCS teams are placed where their
   rating would rank among FBS teams).
   =================================================================== */
const BOT_NATRANK = {"AFA": 95, "HAW": 125, "NEV": 103, "UNM": 55, "NDSU": 64, "NIU": 124, "SJSU": 110, "UNLV": 90, "UTEP": 132, "WYO": 126, "BSU": 41, "CSU": 106, "FRES": 71, "ORST": 51, "SDSU": 85, "TXST": 69, "USU": 87, "WSU": 83, "NMSU": 113, "SAC": 138};
const OPPONENTS = {
 "USC": {
  "natRank": 23,
  "fcs": false
 },
 "Jacksonville State": {
  "natRank": 102,
  "fcs": false
 },
 "Eastern Michigan": {
  "natRank": 127,
  "fcs": false
 },
 "Stanford": {
  "natRank": 105,
  "fcs": false
 },
 "Florida State": {
  "natRank": 33,
  "fcs": false
 },
 "Memphis": {
  "natRank": 62,
  "fcs": false
 },
 "Oklahoma": {
  "natRank": 19,
  "fcs": false
 },
 "Houston": {
  "natRank": 29,
  "fcs": false
 },
 "Duquesne": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Texas": {
  "natRank": 8,
  "fcs": false
 },
 "Oregon": {
  "natRank": 6,
  "fcs": false
 },
 "Fordham": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Iowa": {
  "natRank": 14,
  "fcs": false
 },
 "Idaho State": {
  "fcs": true,
  "equivRank": 125,
  "strong": false,
  "fcsRank": 12
 },
 "Mercyhurst": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Portland State": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Central Michigan": {
  "natRank": 122,
  "fcs": false
 },
 "Mississippi Valley State": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Western Kentucky": {
  "natRank": 116,
  "fcs": false
 },
 "Washington": {
  "natRank": 42,
  "fcs": false
 },
 "Kansas State": {
  "natRank": 32,
  "fcs": false
 },
 "UTSA": {
  "natRank": 73,
  "fcs": false
 },
 "North Texas": {
  "natRank": 67,
  "fcs": false
 },
 "Northern Colorado": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Southern Utah": {
  "fcs": true,
  "equivRank": 137,
  "strong": false
 },
 "Illinois State": {
  "fcs": true,
  "equivRank": 121,
  "strong": false,
  "fcsRank": 8
 },
 "UCLA": {
  "natRank": 11,
  "fcs": false
 },
 "Texas Tech": {
  "natRank": 12,
  "fcs": false
 },
 "Cal Poly": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Texas Southern": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Montana State": {
  "fcs": true,
  "equivRank": 74,
  "strong": true,
  "fcsRank": 1
 },
 "Utah": {
  "natRank": 5,
  "fcs": false
 },
 "Michigan": {
  "natRank": 34,
  "fcs": false
 },
 "Middle Tennessee": {
  "natRank": 130,
  "fcs": false
 },
 "BYU": {
  "natRank": 21,
  "fcs": false
 },
 "South Dakota": {
  "fcs": true,
  "equivRank": 103,
  "strong": true,
  "fcsRank": 4
 },
 "James Madison": {
  "natRank": 43,
  "fcs": false
 },
 "Arizona": {
  "natRank": 36,
  "fcs": false
 },
 "Montana": {
  "fcs": true,
  "equivRank": 111,
  "strong": false,
  "fcsRank": 6
 },
 "Toledo": {
  "natRank": 60,
  "fcs": false
 },
 "Akron": {
  "natRank": 134,
  "fcs": false
 },
 "Georgia State": {
  "natRank": 78,
  "fcs": false
 },
 "Western Michigan": {
  "natRank": 92,
  "fcs": false
 },
 "Incarnate Word": {
  "fcs": true,
  "equivRank": 139,
  "strong": false
 },
 "Troy": {
  "natRank": 97,
  "fcs": false
 },
 "Massachusetts": {
  "natRank": 129,
  "fcs": false
 },
 "Rice": {
  "natRank": 119,
  "fcs": false
 },
 "Navy": {
  "natRank": 101,
  "fcs": false
 },
 "California": {
  "natRank": 79,
  "fcs": false
 }
};
const GAMES = [{"team":"SJSU","week":0,"date":"2026-08-29","opp":"USC","site":"A","pf":26,"pa":42,"exp":-34.0,"stats":{"yds":336,"oppYds":505,"to":0,"oppTo":1,"sacks":2,"sacksAllowed":1,"ypp":6.0,"oppYpp":6.6,"thirdPct":45,"oppThirdPct":69,"explosive":8,"oppExplosive":8}},
{"team":"NDSU","week":0,"date":"2026-08-29","opp":"Jacksonville State","site":"H","pf":33,"pa":7,"exp":16.9,"stats":{"yds":373,"oppYds":170,"to":1,"oppTo":2,"sacks":3,"sacksAllowed":2,"ypp":5.6,"oppYpp":3.1,"thirdPct":36,"oppThirdPct":20,"explosive":9,"oppExplosive":4}},
{"team":"SAC","week":0,"date":"2026-08-29","opp":"Eastern Michigan","site":"A","pf":17,"pa":28,"exp":-4.5,"stats":{"yds":271,"oppYds":348,"to":2,"oppTo":1,"sacks":2,"sacksAllowed":2,"ypp":4.3,"oppYpp":5.1,"thirdPct":21,"oppThirdPct":33,"explosive":5,"oppExplosive":7}},
{"team":"HAW","week":0,"date":"2026-08-29","opp":"Stanford","site":"A","pf":27,"pa":37,"exp":-9.9,"stats":{"yds":325,"oppYds":468,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":2,"ypp":4.3,"oppYpp":6.5,"thirdPct":42,"oppThirdPct":44,"explosive":6,"oppExplosive":10}},
{"team":"NMSU","week":0,"date":"2026-08-29","opp":"Florida State","site":"A","pf":17,"pa":34,"exp":-30.7,"stats":{"yds":319,"oppYds":419,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":3,"ypp":4.8,"oppYpp":6.3,"thirdPct":59,"oppThirdPct":57,"explosive":6,"oppExplosive":10}},
{"team":"UNLV","week":0,"date":"2026-08-29","opp":"Memphis","site":"H","pf":21,"pa":27,"exp":3.0,"stats":{"yds":460,"oppYds":418,"to":0,"oppTo":1,"sacks":1,"sacksAllowed":6,"ypp":5.8,"oppYpp":7.0,"thirdPct":20,"oppThirdPct":27,"explosive":9,"oppExplosive":11}},
{"team":"SJSU","week":1,"date":"2026-09-04","opp":"Eastern Michigan","site":"A","pf":27,"pa":21,"exp":-0.9,"stats":{"yds":453,"oppYds":281,"to":2,"oppTo":1,"sacks":0,"sacksAllowed":1,"ypp":5.9,"oppYpp":4.1,"thirdPct":31,"oppThirdPct":19,"explosive":10,"oppExplosive":2}},
{"team":"UTEP","week":1,"date":"2026-09-04","opp":"Oklahoma","site":"A","pf":0,"pa":51,"exp":-37.5,"stats":{"yds":198,"oppYds":401,"to":2,"oppTo":1,"sacks":1,"sacksAllowed":4,"ypp":3.5,"oppYpp":6.9,"thirdPct":15,"oppThirdPct":55,"explosive":3,"oppExplosive":9}},
{"team":"FRES","week":1,"date":"2026-09-04","opp":"USC","site":"A","pf":0,"pa":39,"exp":-23.3,"stats":{"yds":116,"oppYds":552,"to":2,"oppTo":2,"sacks":0,"sacksAllowed":5,"ypp":2.6,"oppYpp":8.1,"thirdPct":20,"oppThirdPct":62,"explosive":2,"oppExplosive":12}},
{"team":"ORST","week":1,"date":"2026-09-05","opp":"Houston","site":"A","pf":20,"pa":33,"exp":-13.1,"stats":{"yds":402,"oppYds":533,"to":0,"oppTo":2,"sacks":1,"sacksAllowed":4,"ypp":5.5,"oppYpp":7.4,"thirdPct":27,"oppThirdPct":54,"explosive":7,"oppExplosive":13}},
{"team":"AFA","week":1,"date":"2026-09-05","opp":"Duquesne","site":"H","pf":34,"pa":0,"exp":25.8,"stats":{"yds":450,"oppYds":107,"to":0,"oppTo":2,"sacks":1,"sacksAllowed":0,"ypp":5.8,"oppYpp":2.5,"thirdPct":60,"oppThirdPct":27,"explosive":8,"oppExplosive":1}},
{"team":"TXST","week":1,"date":"2026-09-05","opp":"Texas","site":"A","pf":7,"pa":59,"exp":-26.1,"stats":{"yds":349,"oppYds":516,"to":3,"oppTo":1,"sacks":1,"sacksAllowed":2,"ypp":5.0,"oppYpp":7.4,"thirdPct":57,"oppThirdPct":73,"explosive":7,"oppExplosive":13}},
{"team":"BSU","week":1,"date":"2026-09-05","opp":"Oregon","site":"A","pf":27,"pa":34,"exp":-23.8,"stats":{"yds":274,"oppYds":497,"to":0,"oppTo":1,"sacks":1,"sacksAllowed":3,"ypp":4.2,"oppYpp":7.9,"thirdPct":27,"oppThirdPct":33,"explosive":4,"oppExplosive":9}},
{"team":"NDSU","week":1,"date":"2026-09-05","opp":"Fordham","site":"H","pf":38,"pa":0,"exp":38.6,"stats":{"yds":373,"oppYds":135,"to":0,"oppTo":4,"sacks":3,"sacksAllowed":3,"ypp":5.4,"oppYpp":2.8,"thirdPct":50,"oppThirdPct":33,"explosive":8,"oppExplosive":2}},
{"team":"NIU","week":1,"date":"2026-09-05","opp":"Iowa","site":"A","pf":0,"pa":40,"exp":-29.4,"stats":{"yds":120,"oppYds":507,"to":2,"oppTo":1,"sacks":0,"sacksAllowed":6,"ypp":2.2,"oppYpp":6.5,"thirdPct":20,"oppThirdPct":43,"explosive":4,"oppExplosive":10}},
{"team":"CSU","week":1,"date":"2026-09-05","opp":"WYO","site":"H","pf":35,"pa":13,"exp":-4.0,"stats":{"yds":396,"oppYds":273,"to":0,"oppTo":4,"sacks":2,"sacksAllowed":0,"ypp":5.9,"oppYpp":5.2,"thirdPct":47,"oppThirdPct":0,"explosive":7,"oppExplosive":7}},
{"team":"WYO","week":1,"date":"2026-09-05","opp":"CSU","site":"A","pf":13,"pa":35,"exp":4.0,"stats":{"yds":273,"oppYds":396,"to":4,"oppTo":0,"sacks":0,"sacksAllowed":2,"ypp":5.2,"oppYpp":5.9,"thirdPct":0,"oppThirdPct":47,"explosive":7,"oppExplosive":7}},
{"team":"USU","week":1,"date":"2026-09-05","opp":"Idaho State","site":"H","pf":17,"pa":29,"exp":21.3,"stats":{"yds":407,"oppYds":241,"to":4,"oppTo":0,"sacks":2,"sacksAllowed":3,"ypp":4.6,"oppYpp":3.8,"thirdPct":60,"oppThirdPct":33,"explosive":6,"oppExplosive":2}},
{"team":"NMSU","week":1,"date":"2026-09-05","opp":"Mercyhurst","site":"H","pf":51,"pa":14,"exp":27.3,"stats":{"yds":554,"oppYds":237,"to":0,"oppTo":2,"sacks":2,"sacksAllowed":1,"ypp":8.5,"oppYpp":4.1,"thirdPct":54,"oppThirdPct":38,"explosive":11,"oppExplosive":5}},
{"team":"SDSU","week":1,"date":"2026-09-05","opp":"Portland State","site":"H","pf":53,"pa":20,"exp":33.0,"stats":{"yds":394,"oppYds":375,"to":3,"oppTo":3,"sacks":1,"sacksAllowed":1,"ypp":6.3,"oppYpp":4.6,"thirdPct":50,"oppThirdPct":37,"explosive":9,"oppExplosive":4}},
{"team":"HAW","week":1,"date":"2026-09-05","opp":"UNLV","site":"H","pf":6,"pa":21,"exp":-2.9,"stats":{"yds":294,"oppYds":364,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":5,"ypp":3.9,"oppYpp":6.0,"thirdPct":45,"oppThirdPct":47,"explosive":7,"oppExplosive":8}},
{"team":"UNLV","week":1,"date":"2026-09-05","opp":"HAW","site":"A","pf":21,"pa":6,"exp":2.9,"stats":{"yds":364,"oppYds":294,"to":0,"oppTo":1,"sacks":5,"sacksAllowed":1,"ypp":6.0,"oppYpp":3.9,"thirdPct":47,"oppThirdPct":45,"explosive":8,"oppExplosive":7}},
{"team":"UNM","week":1,"date":"2026-09-05","opp":"Central Michigan","site":"H","pf":38,"pa":7,"exp":11.9,"stats":{"yds":364,"oppYds":149,"to":0,"oppTo":2,"sacks":3,"sacksAllowed":2,"ypp":5.3,"oppYpp":3.1,"thirdPct":54,"oppThirdPct":18,"explosive":7,"oppExplosive":2}},
{"team":"SAC","week":1,"date":"2026-09-05","opp":"Mississippi Valley State","site":"H","pf":52,"pa":0,"exp":37.4,"stats":{"yds":453,"oppYds":147,"to":2,"oppTo":1,"sacks":4,"sacksAllowed":0,"ypp":6.5,"oppYpp":2.8,"thirdPct":50,"oppThirdPct":13,"explosive":9,"oppExplosive":2}},
{"team":"NEV","week":1,"date":"2026-09-05","opp":"Western Kentucky","site":"H","pf":49,"pa":14,"exp":-1.7,"stats":{"yds":486,"oppYds":367,"to":1,"oppTo":2,"sacks":3,"sacksAllowed":0,"ypp":8.4,"oppYpp":4.5,"thirdPct":50,"oppThirdPct":35,"explosive":9,"oppExplosive":5}},
{"team":"WSU","week":1,"date":"2026-09-06","opp":"Washington","site":"A","pf":10,"pa":24,"exp":-15.6,"stats":{"yds":242,"oppYds":402,"to":3,"oppTo":0,"sacks":0,"sacksAllowed":3,"ypp":4.3,"oppYpp":6.3,"thirdPct":0,"oppThirdPct":33,"explosive":3,"oppExplosive":10}},
{"team":"WSU","week":2,"date":"2026-09-12","opp":"Kansas State","site":"A","pf":7,"pa":34,"exp":-14.1,"stats":{"yds":166,"oppYds":487,"to":1,"oppTo":2,"sacks":0,"sacksAllowed":4,"ypp":3.3,"oppYpp":6.6,"thirdPct":17,"oppThirdPct":62,"explosive":4,"oppExplosive":7}},
{"team":"USU","week":2,"date":"2026-09-12","opp":"Washington","site":"A","pf":14,"pa":16,"exp":-28.4,"stats":{"yds":271,"oppYds":356,"to":3,"oppTo":0,"sacks":2,"sacksAllowed":3,"ypp":4.7,"oppYpp":4.8,"thirdPct":46,"oppThirdPct":35,"explosive":6,"oppExplosive":6}},
{"team":"TXST","week":2,"date":"2026-09-12","opp":"UTSA","site":"H","pf":26,"pa":31,"exp":-3.8,"stats":{"yds":481,"oppYds":398,"to":3,"oppTo":0,"sacks":0,"sacksAllowed":0,"ypp":6.0,"oppYpp":5.4,"thirdPct":53,"oppThirdPct":20,"explosive":7,"oppExplosive":6}},
{"team":"UNLV","week":2,"date":"2026-09-12","opp":"North Texas","site":"A","pf":6,"pa":44,"exp":-7.8,"stats":{"yds":301,"oppYds":444,"to":4,"oppTo":0,"sacks":1,"sacksAllowed":4,"ypp":4.2,"oppYpp":6.6,"thirdPct":41,"oppThirdPct":54,"explosive":6,"oppExplosive":12}},
{"team":"UNM","week":2,"date":"2026-09-12","opp":"Mercyhurst","site":"H","pf":70,"pa":7,"exp":42.7,"stats":{"yds":460,"oppYds":155,"to":0,"oppTo":6,"sacks":5,"sacksAllowed":2,"ypp":6.6,"oppYpp":2.8,"thirdPct":38,"oppThirdPct":15,"explosive":10,"oppExplosive":4}},
{"team":"WYO","week":2,"date":"2026-09-12","opp":"Northern Colorado","site":"H","pf":21,"pa":13,"exp":24.2,"stats":{"yds":304,"oppYds":345,"to":2,"oppTo":2,"sacks":3,"sacksAllowed":1,"ypp":5.1,"oppYpp":5.6,"thirdPct":42,"oppThirdPct":33,"explosive":10,"oppExplosive":7}},
{"team":"BSU","week":2,"date":"2026-09-12","opp":"Memphis","site":"H","pf":38,"pa":20,"exp":12.3,"stats":{"yds":578,"oppYds":519,"to":0,"oppTo":1,"sacks":2,"sacksAllowed":0,"ypp":7.7,"oppYpp":10.0,"thirdPct":46,"oppThirdPct":12,"explosive":13,"oppExplosive":10}},
{"team":"CSU","week":2,"date":"2026-09-12","opp":"Southern Utah","site":"H","pf":58,"pa":24,"exp":12.8,"stats":{"yds":678,"oppYds":442,"to":1,"oppTo":4,"sacks":3,"sacksAllowed":1,"ypp":9.8,"oppYpp":6.9,"thirdPct":53,"oppThirdPct":43,"explosive":12,"oppExplosive":12}},
{"team":"NIU","week":2,"date":"2026-09-12","opp":"Illinois State","site":"H","pf":24,"pa":28,"exp":2.1,"stats":{"yds":308,"oppYds":254,"to":2,"oppTo":2,"sacks":3,"sacksAllowed":3,"ypp":4.7,"oppYpp":4.0,"thirdPct":40,"oppThirdPct":64,"explosive":5,"oppExplosive":5}},
{"team":"SDSU","week":2,"date":"2026-09-12","opp":"UCLA","site":"A","pf":10,"pa":28,"exp":-15.8,"stats":{"yds":189,"oppYds":365,"to":1,"oppTo":1,"sacks":2,"sacksAllowed":2,"ypp":3.4,"oppYpp":5.5,"thirdPct":17,"oppThirdPct":36,"explosive":2,"oppExplosive":6}},
{"team":"ORST","week":2,"date":"2026-09-12","opp":"Texas Tech","site":"H","pf":24,"pa":35,"exp":-16.1,"stats":{"yds":472,"oppYds":352,"to":1,"oppTo":1,"sacks":4,"sacksAllowed":2,"ypp":6.6,"oppYpp":4.7,"thirdPct":27,"oppThirdPct":47,"explosive":11,"oppExplosive":5}},
{"team":"SJSU","week":2,"date":"2026-09-12","opp":"Cal Poly","site":"H","pf":30,"pa":20,"exp":20.5,"stats":{"yds":493,"oppYds":340,"to":1,"oppTo":2,"sacks":4,"sacksAllowed":0,"ypp":6.3,"oppYpp":4.9,"thirdPct":25,"oppThirdPct":50,"explosive":9,"oppExplosive":9}},
{"team":"UTEP","week":2,"date":"2026-09-12","opp":"Texas Southern","site":"H","pf":51,"pa":10,"exp":25.2,"stats":{"yds":491,"oppYds":211,"to":1,"oppTo":2,"sacks":2,"sacksAllowed":1,"ypp":9.1,"oppYpp":3.4,"thirdPct":50,"oppThirdPct":35,"explosive":8,"oppExplosive":4}},
{"team":"AFA","week":2,"date":"2026-09-12","opp":"NDSU","site":"H","pf":32,"pa":38,"exp":-4.7,"stats":{"yds":386,"oppYds":374,"to":1,"oppTo":1,"sacks":0,"sacksAllowed":1,"ypp":5.8,"oppYpp":6.2,"thirdPct":43,"oppThirdPct":33,"explosive":6,"oppExplosive":8}},
{"team":"NDSU","week":2,"date":"2026-09-12","opp":"AFA","site":"A","pf":38,"pa":32,"exp":4.7,"stats":{"yds":374,"oppYds":386,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":0,"ypp":6.2,"oppYpp":5.8,"thirdPct":33,"oppThirdPct":43,"explosive":8,"oppExplosive":6}},
{"team":"NEV","week":2,"date":"2026-09-12","opp":"Montana State","site":"H","pf":7,"pa":20,"exp":-1.3,"stats":{"yds":349,"oppYds":330,"to":4,"oppTo":0,"sacks":3,"sacksAllowed":0,"ypp":4.9,"oppYpp":5.2,"thirdPct":31,"oppThirdPct":38,"explosive":5,"oppExplosive":7}},
{"team":"FRES","week":2,"date":"2026-09-12","opp":"SAC","site":"H","pf":49,"pa":3,"exp":12.2,"stats":{"yds":542,"oppYds":262,"to":0,"oppTo":1,"sacks":1,"sacksAllowed":0,"ypp":8.6,"oppYpp":4.0,"thirdPct":50,"oppThirdPct":23,"explosive":10,"oppExplosive":4}},
{"team":"SAC","week":2,"date":"2026-09-12","opp":"FRES","site":"A","pf":3,"pa":49,"exp":-12.2,"stats":{"yds":262,"oppYds":542,"to":1,"oppTo":0,"sacks":0,"sacksAllowed":1,"ypp":4.0,"oppYpp":8.6,"thirdPct":23,"oppThirdPct":50,"explosive":4,"oppExplosive":10}},
{"team":"HAW","week":2,"date":"2026-09-12","opp":"NMSU","site":"H","pf":29,"pa":19,"exp":4.8,"stats":{"yds":420,"oppYds":380,"to":1,"oppTo":3,"sacks":2,"sacksAllowed":1,"ypp":5.8,"oppYpp":5.8,"thirdPct":33,"oppThirdPct":40,"explosive":7,"oppExplosive":9}},
{"team":"NMSU","week":2,"date":"2026-09-12","opp":"HAW","site":"A","pf":19,"pa":29,"exp":-4.8,"stats":{"yds":380,"oppYds":420,"to":3,"oppTo":1,"sacks":1,"sacksAllowed":2,"ypp":5.8,"oppYpp":5.8,"thirdPct":40,"oppThirdPct":33,"explosive":9,"oppExplosive":7}},
{"team":"TXST","week":3,"date":"2026-09-19","opp":"North Texas","site":"H","pf":49,"pa":35,"exp":-5.9,"stats":{"yds":605,"oppYds":605,"to":0,"oppTo":2,"sacks":0,"sacksAllowed":1,"ypp":8.5,"oppYpp":7.1,"thirdPct":60,"oppThirdPct":67,"explosive":12,"oppExplosive":10}},
{"team":"WYO","week":3,"date":"2026-09-19","opp":"Central Michigan","site":"A","pf":10,"pa":24,"exp":3.0,"stats":{"yds":340,"oppYds":371,"to":2,"oppTo":0,"sacks":0,"sacksAllowed":0,"ypp":5.8,"oppYpp":5.6,"thirdPct":46,"oppThirdPct":38,"explosive":7,"oppExplosive":4}},
{"team":"USU","week":3,"date":"2026-09-19","opp":"Utah","site":"A","pf":0,"pa":33,"exp":-30.8,"stats":{"yds":188,"oppYds":480,"to":2,"oppTo":1,"sacks":1,"sacksAllowed":4,"ypp":3.5,"oppYpp":6.5,"thirdPct":27,"oppThirdPct":59,"explosive":3,"oppExplosive":10}},
{"team":"UTEP","week":3,"date":"2026-09-19","opp":"Michigan","site":"A","pf":17,"pa":52,"exp":-31.5,"stats":{"yds":150,"oppYds":431,"to":1,"oppTo":2,"sacks":1,"sacksAllowed":4,"ypp":3.2,"oppYpp":6.2,"thirdPct":17,"oppThirdPct":69,"explosive":4,"oppExplosive":9}},
{"team":"WSU","week":3,"date":"2026-09-19","opp":"Duquesne","site":"H","pf":48,"pa":7,"exp":33.8,"stats":{"yds":512,"oppYds":185,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":0,"ypp":8.3,"oppYpp":3.6,"thirdPct":67,"oppThirdPct":15,"explosive":12,"oppExplosive":3}},
{"team":"NEV","week":3,"date":"2026-09-19","opp":"Middle Tennessee","site":"A","pf":20,"pa":27,"exp":5.0,"stats":{"yds":280,"oppYds":330,"to":3,"oppTo":0,"sacks":1,"sacksAllowed":1,"ypp":4.8,"oppYpp":4.9,"thirdPct":38,"oppThirdPct":27,"explosive":5,"oppExplosive":3}},
{"team":"CSU","week":3,"date":"2026-09-19","opp":"BYU","site":"H","pf":23,"pa":41,"exp":-17.9,"stats":{"yds":302,"oppYds":559,"to":1,"oppTo":2,"sacks":0,"sacksAllowed":0,"ypp":4.6,"oppYpp":9.6,"thirdPct":50,"oppThirdPct":44,"explosive":5,"oppExplosive":11}},
{"team":"UNM","week":3,"date":"2026-09-19","opp":"Oklahoma","site":"A","pf":6,"pa":14,"exp":-23.0,"stats":{"yds":185,"oppYds":299,"to":0,"oppTo":3,"sacks":1,"sacksAllowed":6,"ypp":3.2,"oppYpp":5.2,"thirdPct":21,"oppThirdPct":47,"explosive":4,"oppExplosive":3}},
{"team":"BSU","week":3,"date":"2026-09-19","opp":"South Dakota","site":"H","pf":38,"pa":24,"exp":20.3,"stats":{"yds":533,"oppYds":279,"to":2,"oppTo":2,"sacks":2,"sacksAllowed":1,"ypp":6.7,"oppYpp":5.6,"thirdPct":62,"oppThirdPct":25,"explosive":8,"oppExplosive":8}},
{"team":"SDSU","week":3,"date":"2026-09-19","opp":"James Madison","site":"H","pf":13,"pa":26,"exp":-0.8,"stats":{"yds":401,"oppYds":417,"to":2,"oppTo":1,"sacks":3,"sacksAllowed":2,"ypp":5.2,"oppYpp":5.6,"thirdPct":41,"oppThirdPct":31,"explosive":7,"oppExplosive":7}},
{"team":"NIU","week":3,"date":"2026-09-19","opp":"Arizona","site":"A","pf":17,"pa":42,"exp":-28.2,"stats":{"yds":341,"oppYds":441,"to":0,"oppTo":1,"sacks":4,"sacksAllowed":2,"ypp":5.1,"oppYpp":6.9,"thirdPct":38,"oppThirdPct":82,"explosive":5,"oppExplosive":10}},
{"team":"SAC","week":3,"date":"2026-09-19","opp":"NDSU","site":"H","pf":10,"pa":31,"exp":-20.8,"stats":{"yds":328,"oppYds":362,"to":3,"oppTo":0,"sacks":0,"sacksAllowed":0,"ypp":5.0,"oppYpp":6.1,"thirdPct":47,"oppThirdPct":50,"explosive":9,"oppExplosive":9}},
{"team":"NDSU","week":3,"date":"2026-09-19","opp":"SAC","site":"A","pf":31,"pa":10,"exp":20.8,"stats":{"yds":362,"oppYds":328,"to":0,"oppTo":3,"sacks":0,"sacksAllowed":0,"ypp":6.1,"oppYpp":5.0,"thirdPct":50,"oppThirdPct":47,"explosive":9,"oppExplosive":9}},
{"team":"ORST","week":3,"date":"2026-09-19","opp":"Montana","site":"H","pf":52,"pa":17,"exp":9.8,"stats":{"yds":508,"oppYds":338,"to":1,"oppTo":2,"sacks":2,"sacksAllowed":0,"ypp":7.5,"oppYpp":4.7,"thirdPct":50,"oppThirdPct":29,"explosive":12,"oppExplosive":2}},
{"team":"SJSU","week":3,"date":"2026-09-19","opp":"FRES","site":"H","pf":10,"pa":26,"exp":-4.6,"stats":{"yds":335,"oppYds":344,"to":4,"oppTo":0,"sacks":1,"sacksAllowed":6,"ypp":4.8,"oppYpp":5.1,"thirdPct":35,"oppThirdPct":31,"explosive":8,"oppExplosive":10}},
{"team":"FRES","week":3,"date":"2026-09-19","opp":"SJSU","site":"A","pf":26,"pa":10,"exp":4.6,"stats":{"yds":344,"oppYds":335,"to":0,"oppTo":4,"sacks":6,"sacksAllowed":1,"ypp":5.1,"oppYpp":4.8,"thirdPct":31,"oppThirdPct":35,"explosive":10,"oppExplosive":8}},
{"team":"CSU","week":4,"date":"2026-09-26","opp":"UTSA","site":"A","pf":45,"pa":59,"exp":-12.4,"stats":{"yds":500,"oppYds":542,"to":1,"oppTo":0,"sacks":1,"sacksAllowed":1,"ypp":6.4,"oppYpp":7.5,"thirdPct":35,"oppThirdPct":56,"explosive":6,"oppExplosive":11}},
{"team":"SDSU","week":4,"date":"2026-09-26","opp":"Toledo","site":"A","pf":16,"pa":41,"exp":-10.2,"stats":{"yds":296,"oppYds":494,"to":2,"oppTo":0,"sacks":0,"sacksAllowed":3,"ypp":4.4,"oppYpp":7.1,"thirdPct":21,"oppThirdPct":53,"explosive":4,"oppExplosive":8}},
{"team":"UNLV","week":4,"date":"2026-09-26","opp":"Akron","site":"A","pf":38,"pa":10,"exp":6.7,"stats":{"yds":493,"oppYds":301,"to":0,"oppTo":3,"sacks":3,"sacksAllowed":0,"ypp":7.8,"oppYpp":5.2,"thirdPct":46,"oppThirdPct":38,"explosive":10,"oppExplosive":7}},
{"team":"NIU","week":4,"date":"2026-09-26","opp":"Georgia State","site":"A","pf":14,"pa":35,"exp":-11.5,"stats":{"yds":432,"oppYds":342,"to":2,"oppTo":2,"sacks":0,"sacksAllowed":6,"ypp":5.9,"oppYpp":6.0,"thirdPct":23,"oppThirdPct":50,"explosive":12,"oppExplosive":9}},
{"team":"WYO","week":4,"date":"2026-09-26","opp":"HAW","site":"H","pf":27,"pa":10,"exp":0.3,"stats":{"yds":387,"oppYds":328,"to":0,"oppTo":0,"sacks":3,"sacksAllowed":3,"ypp":6.3,"oppYpp":4.9,"thirdPct":50,"oppThirdPct":36,"explosive":13,"oppExplosive":7}},
{"team":"HAW","week":4,"date":"2026-09-26","opp":"WYO","site":"A","pf":10,"pa":27,"exp":-0.3,"stats":{"yds":328,"oppYds":387,"to":0,"oppTo":0,"sacks":3,"sacksAllowed":3,"ypp":4.9,"oppYpp":6.3,"thirdPct":36,"oppThirdPct":50,"explosive":7,"oppExplosive":13}},
{"team":"BSU","week":4,"date":"2026-09-26","opp":"Western Michigan","site":"A","pf":32,"pa":7,"exp":3.8,"stats":{"yds":377,"oppYds":223,"to":0,"oppTo":1,"sacks":1,"sacksAllowed":0,"ypp":5.8,"oppYpp":4.4,"thirdPct":71,"oppThirdPct":18,"explosive":8,"oppExplosive":5}},
{"team":"NMSU","week":4,"date":"2026-09-26","opp":"UNM","site":"H","pf":18,"pa":42,"exp":-11.6,"stats":{"yds":405,"oppYds":430,"to":3,"oppTo":0,"sacks":2,"sacksAllowed":3,"ypp":5.9,"oppYpp":6.7,"thirdPct":43,"oppThirdPct":42,"explosive":10,"oppExplosive":12}},
{"team":"UNM","week":4,"date":"2026-09-26","opp":"NMSU","site":"A","pf":42,"pa":18,"exp":11.6,"stats":{"yds":430,"oppYds":405,"to":0,"oppTo":3,"sacks":3,"sacksAllowed":2,"ypp":6.7,"oppYpp":5.9,"thirdPct":42,"oppThirdPct":43,"explosive":12,"oppExplosive":10}},
{"team":"TXST","week":4,"date":"2026-09-26","opp":"Incarnate Word","site":"H","pf":63,"pa":10,"exp":19.5,"stats":{"yds":658,"oppYds":358,"to":1,"oppTo":2,"sacks":4,"sacksAllowed":1,"ypp":9.5,"oppYpp":4.0,"thirdPct":71,"oppThirdPct":30,"explosive":12,"oppExplosive":6}},
{"team":"WSU","week":4,"date":"2026-09-26","opp":"Arizona","site":"H","pf":24,"pa":34,"exp":-2.8,"stats":{"yds":335,"oppYds":447,"to":2,"oppTo":1,"sacks":3,"sacksAllowed":6,"ypp":4.7,"oppYpp":6.0,"thirdPct":33,"oppThirdPct":47,"explosive":7,"oppExplosive":11}},
{"team":"USU","week":4,"date":"2026-09-26","opp":"Troy","site":"H","pf":21,"pa":10,"exp":6.3,"stats":{"yds":413,"oppYds":395,"to":2,"oppTo":3,"sacks":0,"sacksAllowed":1,"ypp":7.0,"oppYpp":4.9,"thirdPct":36,"oppThirdPct":31,"explosive":10,"oppExplosive":5}},
{"team":"UTEP","week":4,"date":"2026-09-26","opp":"ORST","site":"H","pf":7,"pa":33,"exp":-11.7,"stats":{"yds":222,"oppYds":451,"to":1,"oppTo":1,"sacks":0,"sacksAllowed":8,"ypp":3.4,"oppYpp":7.9,"thirdPct":25,"oppThirdPct":50,"explosive":2,"oppExplosive":11}},
{"team":"ORST","week":4,"date":"2026-09-26","opp":"UTEP","site":"A","pf":33,"pa":7,"exp":11.7,"stats":{"yds":451,"oppYds":222,"to":1,"oppTo":1,"sacks":8,"sacksAllowed":0,"ypp":7.9,"oppYpp":3.4,"thirdPct":50,"oppThirdPct":25,"explosive":11,"oppExplosive":2}},
{"team":"SAC","week":4,"date":"2026-09-26","opp":"Massachusetts","site":"H","pf":6,"pa":35,"exp":-1.4,"stats":{"yds":323,"oppYds":333,"to":3,"oppTo":0,"sacks":1,"sacksAllowed":4,"ypp":4.2,"oppYpp":6.3,"thirdPct":40,"oppThirdPct":30,"explosive":4,"oppExplosive":8}},
{"team":"FRES","week":4,"date":"2026-09-26","opp":"Rice","site":"H","pf":38,"pa":24,"exp":17.9,"stats":{"yds":459,"oppYds":463,"to":0,"oppTo":2,"sacks":2,"sacksAllowed":0,"ypp":6.8,"oppYpp":7.3,"thirdPct":46,"oppThirdPct":36,"explosive":14,"oppExplosive":8}},
{"team":"NEV","week":4,"date":"2026-09-26","opp":"AFA","site":"H","pf":33,"pa":36,"exp":-1.6,"stats":{"yds":411,"oppYds":455,"to":0,"oppTo":1,"sacks":1,"sacksAllowed":4,"ypp":6.2,"oppYpp":5.5,"thirdPct":33,"oppThirdPct":44,"explosive":9,"oppExplosive":10}},
{"team":"AFA","week":4,"date":"2026-09-26","opp":"NEV","site":"A","pf":36,"pa":33,"exp":1.6,"stats":{"yds":455,"oppYds":411,"to":1,"oppTo":0,"sacks":4,"sacksAllowed":1,"ypp":5.5,"oppYpp":6.2,"thirdPct":44,"oppThirdPct":33,"explosive":10,"oppExplosive":9}},
{"team":"NMSU","week":5,"date":"2026-10-01","opp":"Western Kentucky","site":"H","pf":34,"pa":13,"exp":-0.8,"stats":{"yds":352,"oppYds":361,"to":1,"oppTo":1,"sacks":6,"sacksAllowed":1,"ypp":5.9,"oppYpp":4.8,"thirdPct":17,"oppThirdPct":39,"explosive":9,"oppExplosive":7}},
{"team":"AFA","week":5,"date":"2026-10-03","opp":"Navy","site":"H","pf":14,"pa":9,"exp":7.2,"stats":{"yds":270,"oppYds":253,"to":2,"oppTo":1,"sacks":1,"sacksAllowed":0,"ypp":3.8,"oppYpp":5.3,"thirdPct":50,"oppThirdPct":9,"explosive":4,"oppExplosive":4}},
{"team":"UNLV","week":5,"date":"2026-10-03","opp":"California","site":"H","pf":39,"pa":31,"exp":-0.8,"stats":{"yds":345,"oppYds":464,"to":2,"oppTo":1,"sacks":4,"sacksAllowed":3,"ypp":5.7,"oppYpp":5.6,"thirdPct":38,"oppThirdPct":28,"explosive":8,"oppExplosive":10}},
{"team":"NDSU","week":5,"date":"2026-10-03","opp":"WYO","site":"H","pf":28,"pa":0,"exp":18.1,"stats":{"yds":407,"oppYds":162,"to":1,"oppTo":1,"sacks":3,"sacksAllowed":2,"ypp":5.8,"oppYpp":3.3,"thirdPct":46,"oppThirdPct":18,"explosive":10,"oppExplosive":2}},
{"team":"WYO","week":5,"date":"2026-10-03","opp":"NDSU","site":"A","pf":0,"pa":28,"exp":-18.1,"stats":{"yds":162,"oppYds":407,"to":1,"oppTo":1,"sacks":2,"sacksAllowed":3,"ypp":3.3,"oppYpp":5.8,"thirdPct":18,"oppThirdPct":46,"explosive":2,"oppExplosive":10}},
{"team":"UNM","week":5,"date":"2026-10-03","opp":"UTEP","site":"H","pf":61,"pa":7,"exp":21.1,"stats":{"yds":492,"oppYds":270,"to":1,"oppTo":5,"sacks":4,"sacksAllowed":1,"ypp":7.6,"oppYpp":5.1,"thirdPct":58,"oppThirdPct":33,"explosive":9,"oppExplosive":7}},
{"team":"UTEP","week":5,"date":"2026-10-03","opp":"UNM","site":"A","pf":7,"pa":61,"exp":-21.1,"stats":{"yds":270,"oppYds":492,"to":5,"oppTo":1,"sacks":1,"sacksAllowed":4,"ypp":5.1,"oppYpp":7.6,"thirdPct":33,"oppThirdPct":58,"explosive":7,"oppExplosive":9}},
{"team":"CSU","week":5,"date":"2026-10-03","opp":"ORST","site":"H","pf":26,"pa":56,"exp":-7.8,"stats":{"yds":366,"oppYds":653,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":0,"ypp":6.4,"oppYpp":9.3,"thirdPct":55,"oppThirdPct":88}},
{"team":"ORST","week":5,"date":"2026-10-03","opp":"CSU","site":"A","pf":56,"pa":26,"exp":7.8,"stats":{"yds":653,"oppYds":366,"to":1,"oppTo":1,"sacks":0,"sacksAllowed":1,"ypp":9.3,"oppYpp":6.4,"thirdPct":88,"oppThirdPct":55}},
{"team":"BSU","week":5,"date":"2026-10-03","opp":"USU","site":"H","pf":37,"pa":18,"exp":15.7,"stats":{"yds":429,"oppYds":345,"to":1,"oppTo":1,"sacks":6,"sacksAllowed":1,"ypp":6.9,"oppYpp":5.9,"thirdPct":62,"oppThirdPct":31,"explosive":6,"oppExplosive":9}},
{"team":"USU","week":5,"date":"2026-10-03","opp":"BSU","site":"A","pf":18,"pa":37,"exp":-15.7,"stats":{"yds":345,"oppYds":429,"to":1,"oppTo":1,"sacks":1,"sacksAllowed":6,"ypp":5.9,"oppYpp":6.9,"thirdPct":31,"oppThirdPct":62,"explosive":9,"oppExplosive":6}},
{"team":"WSU","week":5,"date":"2026-10-03","opp":"FRES","site":"H","pf":6,"pa":26,"exp":6.0,"stats":{"yds":182,"oppYds":375,"to":2,"oppTo":1,"sacks":1,"sacksAllowed":5,"ypp":3.1,"oppYpp":5.5,"thirdPct":21,"oppThirdPct":35,"explosive":3,"oppExplosive":7}},
{"team":"FRES","week":5,"date":"2026-10-03","opp":"WSU","site":"A","pf":26,"pa":6,"exp":-6.0,"stats":{"yds":375,"oppYds":182,"to":1,"oppTo":2,"sacks":5,"sacksAllowed":1,"ypp":5.5,"oppYpp":3.1,"thirdPct":35,"oppThirdPct":21,"explosive":7,"oppExplosive":3}},
{"team":"SDSU","week":5,"date":"2026-10-03","opp":"TXST","site":"H","pf":31,"pa":29,"exp":-2.7,"stats":{"yds":239,"oppYds":565,"to":0,"oppTo":2,"sacks":3,"sacksAllowed":0,"ypp":4.6,"oppYpp":5.5,"thirdPct":10,"oppThirdPct":42,"explosive":6,"oppExplosive":13}},
{"team":"TXST","week":5,"date":"2026-10-03","opp":"SDSU","site":"A","pf":29,"pa":31,"exp":2.7,"stats":{"yds":565,"oppYds":239,"to":2,"oppTo":0,"sacks":0,"sacksAllowed":3,"ypp":5.5,"oppYpp":4.6,"thirdPct":42,"oppThirdPct":10,"explosive":13,"oppExplosive":6}},
{"team":"HAW","week":5,"date":"2026-10-03","opp":"SJSU","site":"H","pf":16,"pa":20,"exp":-1.2,"stats":{"yds":438,"oppYds":324,"to":2,"oppTo":0,"sacks":2,"sacksAllowed":3,"ypp":7.0,"oppYpp":5.2,"thirdPct":31,"oppThirdPct":27,"explosive":7,"oppExplosive":4}},
{"team":"SJSU","week":5,"date":"2026-10-03","opp":"HAW","site":"A","pf":20,"pa":16,"exp":1.2,"stats":{"yds":324,"oppYds":438,"to":0,"oppTo":2,"sacks":3,"sacksAllowed":2,"ypp":5.2,"oppYpp":7.0,"thirdPct":27,"oppThirdPct":31,"explosive":4,"oppExplosive":7}}];
const NEXT = {
 "AFA": "at Northern Illinois",
 "HAW": "at Arizona State",
 "NEV": "at UTEP",
 "UNM": "Bye",
 "NDSU": "at UNLV",
 "NIU": "vs Air Force",
 "SJSU": "vs Wyoming",
 "UNLV": "vs North Dakota State",
 "UTEP": "vs Nevada",
 "WYO": "at San José State",
 "BSU": "at Fresno State",
 "CSU": "Bye",
 "FRES": "vs Boise State",
 "ORST": "vs San Diego State",
 "SDSU": "at Oregon State",
 "TXST": "Bye",
 "USU": "vs Washington State",
 "WSU": "at Utah State",
 "NMSU": "at Florida International",
 "SAC": "at Bowling Green"
};
const CURRENT_WEEK = 5;
